"""
EraLang Native C Transpiler Backend
Transpiles EraLang AST into optimized ANSI C99 code for bare-metal native machine compilation.
"""
import os
import subprocess
import shutil
from typing import List, Dict, Any, Optional
from .ast_nodes import (
    Program, Stmt, Expr, LetStmt, VarStmt, AssignStmt, FnDecl, ReturnStmt,
    ForStmt, WhileStmt, BreakStmt, ContinueStmt, StructDecl, EnumDecl, ExprStmt,
    LiteralExpr, IdentifierExpr, BinaryExpr, UnaryExpr, CallExpr, MemberExpr,
    IndexExpr, ArrayLitExpr, BlockExpr, IfExpr
)
from .token import TokenType


class CTranspiler:
    def __init__(self):
        self.output: List[str] = []
        self.indent_level = 0
        self.struct_names: List[str] = []
        self.enum_names: List[str] = []

    def _emit(self, line: str):
        self.output.append("    " * self.indent_level + line)

    def transpile(self, program: Program) -> str:
        self.output = []
        
        # 1. Header & Runtime Definitions
        self.output.append("/* Auto-Generated by EraLang 2.0 Native C Transpiler */")
        self.output.append("#include <stdio.h>")
        self.output.append("#include <stdlib.h>")
        self.output.append("#include <stdbool.h>")
        self.output.append("#include <string.h>")
        self.output.append("#include <math.h>\n")

        self.output.append("// EraLang Core Runtime Types")
        self.output.append("typedef struct { bool is_some; double value; } EraOption;")
        self.output.append("typedef struct { bool is_ok; double value; const char* err; } EraResult;\n")
        self.output.append("static inline EraOption EraSome(double v) { EraOption o = {true, v}; return o; }")
        self.output.append("static inline EraOption EraNone(void) { EraOption o = {false, 0.0}; return o; }")
        self.output.append("static inline EraResult EraOk(double v) { EraResult r = {true, v, NULL}; return r; }")
        self.output.append("static inline EraResult EraErr(const char* e) { EraResult r = {false, 0.0, e}; return r; }\n")
        self.output.append("static inline void era_print_str(const char* s) { printf(\"%s\\n\", s); }")
        self.output.append("static inline void era_print_num(double n) { printf(\"%g\\n\", n); }\n")

        # 2. Forward Declarations
        for stmt in program.statements:
            if isinstance(stmt, StructDecl):
                self.output.append(f"typedef struct {stmt.name} {stmt.name};")
            elif isinstance(stmt, EnumDecl):
                self.output.append(f"typedef enum {stmt.name} {stmt.name};")
        self.output.append("")

        # 3. Struct & Enum Type Definitions
        for stmt in program.statements:
            if isinstance(stmt, StructDecl):
                self._transpile_struct_decl(stmt)
            elif isinstance(stmt, EnumDecl):
                self._transpile_enum_decl(stmt)

        # 4. Functions
        for stmt in program.statements:
            if isinstance(stmt, FnDecl):
                self._transpile_fn_decl(stmt)

        # 5. Main Execution Function
        self.output.append("\nint main(int argc, char** argv) {")
        self.indent_level += 1

        for stmt in program.statements:
            if not isinstance(stmt, (StructDecl, EnumDecl, FnDecl)):
                self._transpile_stmt(stmt)

        self._emit("return 0;")
        self.indent_level -= 1
        self.output.append("}\n")

        return "\n".join(self.output)

    def _transpile_struct_decl(self, stmt: StructDecl):
        self.struct_names.append(stmt.name)
        self.output.append(f"struct {stmt.name} {{")
        self.indent_level += 1
        for field in stmt.fields:
            c_type = "double"
            t = field.type_annotation or ""
            if t == "int": c_type = "long long"
            elif t == "string": c_type = "const char*"
            elif t == "bool": c_type = "bool"
            elif t in self.struct_names: c_type = t
            self._emit(f"{c_type} {field.name};")
        self.indent_level -= 1
        self.output.append("};\n")

    def _transpile_enum_decl(self, stmt: EnumDecl):
        self.enum_names.append(stmt.name)
        self.output.append(f"enum {stmt.name} {{")
        self.indent_level += 1
        for variant in stmt.variants:
            self._emit(f"{stmt.name}_{variant},")
        self.indent_level -= 1
        self.output.append("};\n")

    def _transpile_fn_decl(self, stmt: FnDecl):
        ret_type = "double"
        if stmt.return_type == "int": ret_type = "long long"
        elif stmt.return_type == "string": ret_type = "const char*"
        elif stmt.return_type == "bool": ret_type = "bool"
        elif stmt.return_type == "void": ret_type = "void"

        params = []
        for p in stmt.params:
            p_type = "double"
            if p.type_name == "int": p_type = "long long"
            elif p.type_name == "string": p_type = "const char*"
            elif p.type_name == "bool": p_type = "bool"
            params.append(f"{p_type} {p.name}")

        param_str = ", ".join(params) if params else "void"
        self.output.append(f"\n{ret_type} {stmt.name}({param_str}) {{")
        self.indent_level += 1
        self._transpile_stmt(stmt.body)
        self.indent_level -= 1
        self.output.append("}")

    def _transpile_stmt(self, stmt: Stmt):
        if isinstance(stmt, (LetStmt, VarStmt)):
            init_code = self._transpile_expr(stmt.initializer)
            t = stmt.type_annotation or ""
            c_type = "double"
            if t == "int": c_type = "long long"
            elif t == "string": c_type = "const char*"
            elif t == "bool": c_type = "bool"
            elif t in self.struct_names: c_type = t
            elif t in self.enum_names: c_type = t
            elif isinstance(stmt.initializer, LiteralExpr):
                if stmt.initializer.type_name == "int": c_type = "long long"
                elif stmt.initializer.type_name == "string": c_type = "const char*"
                elif stmt.initializer.type_name == "bool": c_type = "bool"
            elif isinstance(stmt.initializer, CallExpr) and isinstance(stmt.initializer.callee, IdentifierExpr) and stmt.initializer.callee.name in self.struct_names:
                c_type = stmt.initializer.callee.name
            elif isinstance(stmt.initializer, MemberExpr) and isinstance(stmt.initializer.target, IdentifierExpr) and stmt.initializer.target.name in self.enum_names:
                c_type = stmt.initializer.target.name

            prefix = "const " if isinstance(stmt, LetStmt) else ""
            self._emit(f"{prefix}{c_type} {stmt.name} = {init_code};")

        elif isinstance(stmt, AssignStmt):
            target = self._transpile_expr(stmt.target)
            val = self._transpile_expr(stmt.value)
            self._emit(f"{target} = {val};")

        elif isinstance(stmt, ReturnStmt):
            if stmt.value:
                self._emit(f"return {self._transpile_expr(stmt.value)};")
            else:
                self._emit("return;")

        elif isinstance(stmt, ExprStmt):
            expr_code = self._transpile_expr(stmt.expression)
            self._emit(f"{expr_code};")

        elif isinstance(stmt, BlockExpr):
            for s in stmt.statements:
                self._transpile_stmt(s)

        elif isinstance(stmt, ForStmt):
            # Try to extract range bounds if ForStmt iterable is RangeExpr
            from .ast_nodes import RangeExpr as _RangeExpr
            if isinstance(stmt.iterable, _RangeExpr):
                start_code = self._transpile_expr(stmt.iterable.start)
                end_code = self._transpile_expr(stmt.iterable.end)
                op = "<" if stmt.iterable.half_open else "<="
                self._emit(f"for (long long {stmt.var_name} = {start_code}; {stmt.var_name} {op} {end_code}; {stmt.var_name}++) {{")
            else:
                iter_code = self._transpile_expr(stmt.iterable)
                self._emit(f"// Era For over non-range iterable: {iter_code}")
                self._emit(f"for (long long {stmt.var_name} = 0; {stmt.var_name} < 10; {stmt.var_name}++) {{")
            self.indent_level += 1
            self._transpile_stmt(stmt.body)
            self.indent_level -= 1
            self._emit("}")

        elif isinstance(stmt, WhileStmt):
            cond = self._transpile_expr(stmt.condition)
            self._emit(f"while ({cond}) {{")
            self.indent_level += 1
            self._transpile_stmt(stmt.body)
            self.indent_level -= 1
            self._emit("}")

    def _transpile_expr(self, expr: Expr) -> str:
        if isinstance(expr, LiteralExpr):
            if expr.type_name == "string":
                return f'"{expr.value}"'
            elif expr.type_name == "bool":
                return "true" if expr.value else "false"
            return str(expr.value)

        elif isinstance(expr, IdentifierExpr):
            return expr.name

        elif isinstance(expr, BinaryExpr):
            left = self._transpile_expr(expr.left)
            right = self._transpile_expr(expr.right)
            op = expr.operator.lexeme
            return f"({left} {op} {right})"

        elif isinstance(expr, UnaryExpr):
            right = self._transpile_expr(expr.right)
            op = "!" if expr.operator.type == TokenType.NOT else expr.operator.lexeme
            return f"({op}{right})"

        elif isinstance(expr, CallExpr):
            if isinstance(expr.callee, IdentifierExpr) and expr.callee.name == "print":
                arg = self._transpile_expr(expr.arguments[0])
                return f'era_print_str({arg})' if '"' in arg else f'era_print_num({arg})'

            callee = self._transpile_expr(expr.callee)
            args = ", ".join(self._transpile_expr(a) for a in expr.arguments)
            # Struct constructor check
            if isinstance(expr.callee, IdentifierExpr) and expr.callee.name in self.struct_names:
                return f"({expr.callee.name}){{{args}}}"
            return f"{callee}({args})"

        elif isinstance(expr, MemberExpr):
            target = self._transpile_expr(expr.target)
            if isinstance(expr.target, IdentifierExpr) and expr.target.name in self.enum_names:
                return f"{expr.target.name}_{expr.member}"
            return f"{target}.{expr.member}"

        elif isinstance(expr, IndexExpr):
            target = self._transpile_expr(expr.target)
            idx = self._transpile_expr(expr.index)
            return f"{target}[(int)({idx})]"

        elif isinstance(expr, ArrayLitExpr):
            # C array literal not natively supported - emit comment
            elems = ", ".join(self._transpile_expr(e) for e in expr.elements)
            return f"/* array */ {{{elems}}}"

        elif isinstance(expr, IfExpr):
            # 9.0+ Full IfExpr transpilation: emit inline if via statement context
            # For expression context, emit ternary with actual branches
            cond = self._transpile_expr(expr.condition)
            # Try to transpile branches
            then_code = self._transpile_expr(expr.then_branch) if isinstance(expr.then_branch, Expr) else "0"
            if expr.else_branch:
                else_code = self._transpile_expr(expr.else_branch) if isinstance(expr.else_branch, Expr) else "0"
                return f"({cond} ? {then_code} : {else_code})"
            return f"({cond} ? {then_code} : 0)"

        elif isinstance(expr, BlockExpr):
            # Block in expression position - emit comma expression
            if expr.statements:
                # Last statement's expression
                last = expr.statements[-1]
                if isinstance(last, ExprStmt):
                    return self._transpile_expr(last.expression)
            return "0"

        return "0 /* unsupported expr: {} */".format(type(expr).__name__)


def compile_to_native_binary(c_code: str, output_path: str) -> bool:
    """Compiles C code string to native binary executable using gcc or clang."""
    temp_c = output_path + ".c"
    with open(temp_c, "w", encoding="utf-8") as f:
        f.write(c_code)

    compiler = shutil.which("gcc") or shutil.which("clang")
    if compiler:
        cmd = [compiler, "-O3", temp_c, "-o", output_path, "-lm"]
        ret = subprocess.call(cmd)
        if os.path.exists(temp_c):
            os.remove(temp_c)
        return ret == 0
    else:
        print(f"\033[93m[Note] No native C compiler (gcc/clang) found in PATH. Saved standalone C source to '{temp_c}'\033[0m")
        return True
